// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["postgresql://postgres:[fZSIbju5r4WsKiw8]@db.ihfpzqmjadmzbjljfvqn.supabase.co:5432/postgres"],
  },
};
